In [33]:
# Importing Necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import cvxpy as cp

In [34]:
df = pd.read_excel('Data_2B_2023.xlsx')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,1,2,3,4,5,6,7,8
1,NaN,NaN,NaN,NaN,NaN,NaN,US Bond,Intl Bond,Lg Gr,Lg Val,Sm Gr,Sm Val,Dev,Emerg
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,w = 8 x 1,NaN,Sigma = 8 x 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1.0,US Bonds,NaN,0.1934,NaN,0.001005,0.001328,-0.000579,-0.000675,0.000121,0.000128,-0.000445,-0.000437
5,NaN,2.0,Int'l Bonds,NaN,0.2613,NaN,0.001328,0.007277,-0.001307,-0.00061,-0.002237,-0.000989,0.001442,-0.001535
6,NaN,3.0,US Large Growth,NaN,0.1209,NaN,-0.000579,-0.001307,0.059852,0.027588,0.063497,0.023036,0.032967,0.048039
7,NaN,4.0,US Large Value,NaN,0.1209,NaN,-0.000675,-0.00061,0.027588,0.029609,0.026572,0.021465,0.020697,0.029854
8,NaN,5.0,US Small Growth,NaN,0.0134,NaN,0.000121,-0.002237,0.063497,0.026572,0.102488,0.042744,0.039943,0.065994
9,NaN,6.0,US Small Value,NaN,0.0134,NaN,0.000128,-0.000989,0.023036,0.021465,0.042744,0.032056,0.019881,0.032235
10,NaN,7.0,Int'l Dev. Equity,NaN,0.2418,NaN,-0.000445,0.001442,0.032967,0.020697,0.039943,0.019881,0.028355,0.035064
11,NaN,8.0,Int'l Emerg. Equity,NaN,0.0349,NaN,-0.000437,-0.001535,0.048039,0.029854,0.065994,0.032235,0.035064,0.079958

In [57]:
tickers = df['Unnamed: 2'].iloc[4:12].to_list()
weights = df['Unnamed: 4'].loc[4:12]
cov = df[df.columns[6:14]].iloc[4:12]
cov = cov.apply(pd.to_numeric)

In [ ]:
pd.read_csv(,ind)

In [60]:
implied_return = np.dot(np.linalg.inv(cov), weights)
risk_premium = 0.03
tau = 0.0250
views_matrix =

In [61]:
cov

,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
4,0.001005,0.001328,-0.000579,-0.000675,0.000121,0.000128,-0.000445,-0.000437
5,0.001328,0.007277,-0.001307,-0.000610,-0.002237,-0.000989,0.001442,-0.001535
6,-0.000579,-0.001307,0.059852,0.027588,0.063497,0.023036,0.032967,0.048039
7,-0.000675,-0.000610,0.027588,0.029609,0.026572,0.021465,0.020697,0.029854
8,0.000121,-0.002237,0.063497,0.026572,0.102488,0.042744,0.039943,0.065994
9,0.000128,-0.000989,0.023036,0.021465,0.042744,0.032056,0.019881,0.032235
10,-0.000445,0.001442,0.032967,0.020697,0.039943,0.019881,0.028355,0.035064
11,-0.000437,-0.001535,0.048039,0.029854,0.065994,0.032235,0.035064,0.079958

In [ ]:
implied_return

array([235.36703926861247, -18.439963564558905, -8.271514521456275,
       11.198629977994447, -1.6271249348385868, -17.30270650609895,
       35.11269364674931, -4.922294505037679], dtype=object)